### ISSUE TITLE
MotoSpeed CK62 Support

### ISSUE THREAD

**Issue by SmileYzn** [qmk/qmk_firmware#10738]
This have support for MotoSpeed CK62? or just can add suport to it?

**Comment by SmileYzn** [comment]
One small thing is that keyboard is very similiar to TKL61WS if not identical, can be found here:

https://www.velocifiretech.com/product/m2-wireless-mechanical-keyboard/

Any suggestion?

**Comment by tzarc** [comment]
As I mentioned on Discord: [Selecting an ARM MCU](https://docs.qmk.fm/#/platformdev_selecting_arm_mcu).

**Comment by jpventura** [comment]
@Deckweiss @SmileYzn @tzarc is CK62 firmware fully functional (including bluetooth)?

**Comment by SmileYzn** [comment]
Yes, i mean all in keyboard work as expected.
Can you describe better what you want bro?

Thanks for interest

**Comment by jpventura** [comment]
I just bought a [Motospeed CK62][amazon-url] because it was _"budget mechanical keyboard for only $76.70"_ (yes, taxes are really high here).

First day at work I discovered that you have to hold <kbd>FN</kbd>+<kbd>3</kbd> for 5 seconds to enable the arrow keys, **disabling all other keys**. So all you have to do is hold <kbd>FN</kbd>+<kbd>3</kbd> for another 5 seconds and everything is back to normal :facepalm:

I had [**no idea** about the arrow key issues][youtube-url] and if I have to use [AutoKey][reddit-url] to _"solve"_ this issue, I prefer returning the product.

@SmileYzn All I wanna know if flashing this QMK firmware configuration is enough to solve this issue or if you had to replace any hardware component.

[amazon-url]: https://www.amazon.com/dp/B08JZ8VRL9/
[reddit-url]: https://www.reddit.com/r/MechanicalKeyboards/comments/co1agm/motospeed_ck62_function_key/
[youtube-url]: https://youtu.be/ReH0ujmJKiA?t=293

**Comment by SmileYzn** [comment]
QMK do not support this keyboard :|

Anyway i used this script for autohotkey: https://gist.github.com/SmileYzn/e1144778afa2a5eb593e1f9f4ac81601

And now i'm using a GK61 at home, and motospeed at work.

**Comment by brunomf** [comment]
What can we do to bring support for the Motospeed CK62?

**Comment by Krops** [comment]
good keyboard except key mapping and bluetooth connection (prefere 2.4)

**Comment by Krops** [comment]
Here is some info about controller https://www.eevblog.com/forum/microcontrollers/hfd2201kba-any-details-on-this-microcontroller/

**Comment by MichalKonvic** [comment]
I don't have any experience in this, but I found this Reddit post [Motospeed CK62 - firmware update with layer fix!](https://www.reddit.com/r/MechanicalKeyboards/comments/o1gq23/motospeed_ck62_firmware_update_with_layer_fix/). Maybe someone could reverse engineer the [firmware update file](https://drive.google.com/drive/folders/1V_2lQnaxOfI1HgU82aSAClZm92X_Vjio) and create qmk support from it.

**Comment by renatoalencar** [comment]
I also have one and I'm trying to fix this issue, at least for fun. I was able to dump the firmware using a ST-Linkv2 and OpenOCD, it turns the boot pin is pulled to ground already. If anyone would like to join the effort of reverse engineering the firmware. There's a dump for the boot loader and the 64kb flash memory.

[Archive.zip](https://github.com/qmk/qmk_firmware/files/8740576/Archive.zip)

**Comment by HorrorTroll** [comment]
HFD2201KBA is just a rebranded Sonix SN32F248B MCU make by HFD company, for qmk support, there is a community port called SonixQMK

**Comment by brunomf** [comment]
MotoSpeed released a new firmware that improves the mapping a little. Check
their website.

**Comment by Notmynix** [comment]
Anyone know how to turn of caps lock light?

**Comment by tzarc** [comment]
By asking their support, not QMK.
