### ISSUE TITLE
Really odd behavior with LT()

### ISSUE THREAD

**Issue by gordonlew** [qmk/qmk_firmware#1304]
I am trying to implement LT(4, KC_RALT). My fourth layer is a number layer. When I put RALT in and try to raise the layer, instead of numbers I get numbers plus shift, i.e. &*() instead of 7980. When I instead put LALT I get shift plus alt, i.e ‡°·‚ instead of 7890. What's up with that and how can I get this to work?

**Comment by fredizzimo** [comment]
What are you trying to do? Combing LT with modifiers doesn't really make sense, since when held it would switch layers, and when tapped send the modifier, which would immediately get released. 

I guess you want it the other way? As far as I know there's no ready function for it, you would have to make a macro yourself. See the [macro documentation](https://docs.qmk.fm/Macros.html), especially the "Example: Single-key copy/paste (hold to copy, tap to paste)", which shows how to make a custom dual role key.

**Comment by gordonlew** [comment]
Yes, in general it doesn't make sense to tap modifiers, but in Excel, alt functions as a leader key, so it makes sense then to tap it. Thanks for the tip, though! I'll look into whether a custom macro would give me this functionality.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @gordonlew please reopen this or open a new issue.

**Comment by jtojnar** [comment]
Sorry for bumping, I found this thread when searching for the other way round. Apparently, that feature is now implemented and called [Mod Tap](https://docs.qmk.fm/#/mod_tap).
