### ISSUE TITLE
[Feature Request] Unicode Input mode for Windows Alt + decimal

### ISSUE THREAD

**Issue by Tructruc** [qmk/qmk_firmware#14186]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)

## Description

The actuals Unicode Input modes for windows aren't working whit a stock window, but on windows we can type any Unicode symbol with `alt + the decimal value of the symbol` so we need a new input mode which use this functionality of Windows

**Comment by Myridium** [comment]
What exactly is it that you're asking for?

I think that the unicode symbol input requires the user to press Numpad number keys while holding left-alt. Something like that. Unfortunately this will never work well with QMK (or any keyboard) because you can only do this when Numlock is off, and the keyboard has no way to reliably turn Numlock off. It can only toggle the Numlock state by sending a signal to the computer, and it cannot query what the current Numlock state is (not without bi-directional communication which has not been implemented in QMK).

Aside from the Numlock issue, which means you just need to Toggle Numlock manually occasionally,  what is stopping you from implementing this? Hold down Left-Alt, press numpad number keys, then release Left-Alt.

**Comment by fauxpark** [comment]
This "Alt-codes" input method is not actually Unicode - the values correspond to the Windows-1252 codepage, so do not match up 100%, and in fact may be a different codepage when a different language is set. So this is not really possible at all to add to the Unicode feature.
