### ISSUE TITLE
[Bug] QMK opens VIA function Compiled firmware card DFU mode(QMK 打开VIA功能 编译后的固件卡DFU模式)

### ISSUE THREAD

**Issue by biuboom-jun** [qmk/qmk_firmware#14706]
## Describe the Bug
QMK 打开VIA功能 编译后的固件卡DFU模式
QMK opens VIA function Compiled firmware card DFU mode

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:win10 20h2
 - Main control model: ATmega32u4

 - QMK Firmware version:0.13.34

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [1 ] Other:VIA

## How to reproduce the trigger error
Pin setting
ROW：PB2 PB1 PB0 PF0 PD7
COL：PB6 PB5 PB4 PF6 PF5 PF4 PF1 PE6 PB3 PD1 PD2 PD3 PD5
RGB: PB7
VIA_ENABLE  = yes
DIODE_DIRECTION COL2ROW
At this time, after the compiled firmware is downloaded into the main control, the computer still recognizes the DFU mode

## Summary of temporary errors
Pin PB6 cannot be in COL after opening VIA function
Do not enable VIA function, the firmware compiled by COL on pin PB6 can be used normally

**Comment by sigprof** [comment]
One possible reason for the behavior that you are seeing:
* You have some hardware problem that shows up as a stuck key at the (0,0) position in the matrix (or even the whole column connected to PB6 may be shorted in a way that causes all keys in that column to appear as pressed).
* Setting `VIA_ENABLE = yes` automatically sets the `BOOTMAGIC_ENABLE` option, enabling the [Bootmagic Lite](https://docs.qmk.fm/#/feature_bootmagic) support.
* The Bootmagic Lite code runs early during startup, detects that the key at the (0,0) position in the matrix is pressed and immediately jumps to the bootloader instead of starting the firmware.
