### ISSUE TITLE
Request: Beta Docs Redirect

### ISSUE THREAD

**Issue by redxtech** [qmk/qmk_firmware#15735]
I've been learning how to use qmk recently, and I'm loving it. What I'm not loving is the way that every time I google how to do something with qmk, every single result is to the beta docs site, which isn't live anymore.

Is there any way to set up a redirect to the equivalent page in the live docs?

**Comment by AffluentOwl** [comment]
Bruh, seriously, I was just about to open this issue. docs.qmk.fm hasn't been crawled by Google since 2017 no Google links other than the home page work. Likely because the docs are rendered entirely on the client side using javascript, and have hashbang mode URL's instead of HTML5 URL's.

What's the point of documentation if nobody can find it or search through it for the relevant section?

**Comment by tzarc** [comment]
`beta.docs.qmk.fm` was out of date by more than 6 months, so wasn't relevant to QMK as of today anyway.
You can thank Travis CI and their gutting of open-source free execution time for that.

We have an alternative in the pipeline, but because of the scale of the docs it's taking some time. For now, sit tight.
