### ISSUE TITLE
[Feature Request] Add Keychron Q3

### ISSUE THREAD

**Issue by ibootstrapper** [qmk/qmk_firmware#16812]
### Support for KeyChron Q3 Keyboard

**Comment by yanfali** [comment]
As soon as it hits firmware it should work in configurator.

**Comment by IBNobody** [comment]
Some of the delay of getting Q3 into Firmware might be because those of us with Q3 keyboards with encoders are reporting that the encoder is skipping events when the Q3 is loaded with compiled-from-source .bins. (It's not sampling the encoder fast enough to detect the required pulse edge transitions that indicate encoder turn direction.)

**Comment by ibootstrapper** [comment]
Yes, i'm aware of it. I am actually waiting to receive the knob version and will work towards a fix if one isn't present by the time i get it. the knob issue is across al Q knob keyboards

**Comment by IBNobody** [comment]
That's good to know. I've troubleshot the problem down to the pin sampling level in encoder.c and witnessed the missing A and B line transition states, but I'm not sure how to increase the sampling rate. Is the culprit the overall matrix scan frequency of 188-191 for my board?

**Comment by ibootstrapper** [comment]
great, can you mark the function for me? will be easier to find when i get the keyboard. Thanks!

**Comment by IBNobody** [comment]
encoder_read:

https://github.com/qmk/qmk_firmware/blob/8de4065b099a99bcffe436a038616b0c31ade7c3/quantum/encoder.c#L140

encoder_update called by encoder_read:

https://github.com/qmk/qmk_firmware/blob/8de4065b099a99bcffe436a038616b0c31ade7c3/quantum/encoder.c#L107

This is the line in encoder_read that reads the pins.
https://github.com/qmk/qmk_firmware/blob/8de4065b099a99bcffe436a038616b0c31ade7c3/quantum/encoder.c#L144

And for this encoder, it needs to see 4 separate edges on the pulse on a counterclockwise turn: 

I'm using the format of (pin A state, pin B state)

- (1,1) to (1,0)
- (1,0) to (0,0)
- (0,0) to (0,1)
- (0,1) to (1,1)

Sometimes it just misses the edge, usually the 3rd or 4th state where pins A and B are rising.

**Comment by IBNobody** [comment]
@ibootstrapper The issue is clearly related to the matrix scan frequency. I played around with the ChibiOS settings CH_CFG_ST_FREQUENCY and was able to get the matrix scan frequency up from 191 to 600+ by turning off features and saw that the number of dropped encoder ticks was reduced but not eliminated. So we just need to get the scan frequency up above this.

The keyboard advertises a 1000Hz polling rate. One would think that this would mean that the keyboard scan rate could also achieve this level . . .

**Comment by IBNobody** [comment]
So, the issue is indeed caused by the matrix scan rate. The low scan rate is caused by 3 factors. 

1. CKLED2001 RGB matrix driver - can this be optimized? It's significantly slowing down the scan rate.

2. Custom Matrix (half the columns are using I/O, half using a '595 shift register) - There might be a better way to handle the shift register. Right now, the code shifts in a 0 to trigger a column and then shifts in all F's to clear the register. If instead of clearing the column it just shifted the 0 to the next column, a number of shifting operations could be eliminated and the keyboard matrix scan routine would run faster.

3. CH_CFG_ST_FREQUENCY could be tweaked from 10k to 100k.

If I compile QMK or Keychron's fork with the RGB Matrix disabled, the custom matrix excluded, and CH_CFG_ST_FREQUENCY set to 10k, my matrix scan frequency jumps up to 2400Hz and that is well above the level needed for the matrix encodes to start working.

@lalalademaxiya1 FYI

**Comment by ibootstrapper** [comment]
@IBNobody i just got my Q3 , are you on keychron's discord?

**Comment by IBNobody** [comment]
There's a KC Discord? I'm on the QMK and SonixQMK ones. Throw me an invite. I'm also /u/IBNobody on Reddit.

**Comment by ibootstrapper** [comment]
https://discord.com/invite/HAYbRrTsjN, sent you a friend invite.

**Comment by mwyborski** [comment]
Please check if this PR solves your problem:
https://github.com/qmk/qmk_firmware/pull/16932
You will have to define:
    #define ENCODER_DEFAULT_POS 0x3

**Comment by lokher** [comment]
Please refer to PR 16954

**Comment by IBNobody** [comment]
> Please refer to PR #16954 to fixed encoder issue.

Yes, I can confirm that this fixes the issue on Q3. Now I just need a repo branch that has both the encoder fix and the EEPROM/VIA fix.

**Comment by lokher** [comment]
> 

It's done in playground branch of keychron fork.

**Comment by damianesteban** [comment]
Excellent. This will be great to have.

**Comment by Cr8zyIvan** [comment]
I'm very new to mechanical keyboards and QMK. I acquired the Keychron Q3 with the hopes of getting into it.
- Is this project piloted by the folks at Keychron, or is this purely fan based?
- Is there an estimate when the firmware might available for the Q3?
    - My intention is not to pressure anyone. I know close to nothing about the process involved. This is simply a question of curiosity and eagerness to start coding with QMK!... and not knowing where else to post this question.

Cheers!

**Comment by mwyborski** [comment]
They have a q3 branch:
https://github.com/Keychron/qmk_firmware/tree/keychron-q3

**Comment by Cr8zyIvan** [comment]
Thank you!

**Comment by FWest98** [comment]
> > Please refer to PR #16954 to fixed encoder issue.
> 
> Yes, I can confirm that this fixes the issue on Q3. Now I just need a repo branch that has both the encoder fix and the EEPROM/VIA fix.

I spent some time over the past few days to make such a branch: https://github.com/FWest98/OS-QMK_Firmware/tree/keychron/q3_fwest
It took some time, but it is based on the most recent QMK master with the Q3 definitions and the EEPROM and rotary encoder fixes.

**Comment by pandages** [comment]
> > > Please refer to PR #16954 to fixed encoder issue.
> > 
> > 
> > Yes, I can confirm that this fixes the issue on Q3. Now I just need a repo branch that has both the encoder fix and the EEPROM/VIA fix.
> 
> I spent some time over the past few days to make such a branch: https://github.com/FWest98/OS-QMK_Firmware/tree/keychron/q3_fwest It took some time, but it is based on the most recent QMK master with the Q3 definitions and the EEPROM and rotary encoder fixes.

this looks good! I was thinking about trying to set per-key colors and per-layer effects by modifying QMK itself directly, rather than using VIA.  but I don't know a lot about working with QMK, I'm new to it.

I've seen some really cool videos of effects people have achieved on other keyboards by modifying QMK.

**Comment by pandages** [comment]
I'm not familiar with compiling QMK; I don't have a build environment prepared yet.  But I'd be happy to help review the merges and such.  I'd like to see some of the intended QMK features working on the Keychron Q3.  I'm sure many of the changes will also apply to the other Q-family boards, layout aside.

**Comment by mfin** [comment]
Is there an progress here?

**Comment by ibootstrapper** [comment]
I worked on my own fork here and what i had now support the model with the knob

https://github.com/ibootstrapper/qmk_firmware/commit/909b1ea96e063f90ec0057b766c3aa1e6f9d5699

Please let me know if you experinece any issues

**Comment by ibootstrapper** [comment]
code is here: https://github.com/ibootstrapper/qmk_firmware/tree/playground/keyboards/keychron/q3/q3_ansi_stm32l432_ec11

**Comment by sharpenedblade** [comment]
The keychron fork used by default in the keyboard works properly now.

**Comment by ibootstrapper** [comment]
thanks, i'll check it out

**Comment by tzarc** [comment]
Up to Keychron to submit a PR. Until then we can't do anything about it.

**Comment by sharpenedblade** [comment]
A pr was just submitted, I think this issue should be reopened, or at least changed from not planned.

**Comment by quentin9696** [comment]
Hi Guys, 

@tzarc Any idea on when the feature will be added? I see the PR is ready to merge. 

Thank you for all your work !

**Comment by whyfuture** [comment]
And why is this closed if it's in the main repo?

**Comment by blalor** [comment]
This is being implemented in #16912.

**Comment by whyfuture** [comment]
> This is being implemented in #16912.

Sorry, missed the comment above. Thanks for pointing out.

**Comment by ibootstrapper** [comment]
great, can you mark the function for me? will be easier to find when i get
the keyboard. Thanks!
