### ISSUE TITLE
[Feature Request] Support for Keychron K4 V2

### ISSUE THREAD

**Issue by Bianks84** [qmk/qmk_firmware#17002]
As the title states, looking for support for Keychron K4.
The keyboard supports RGB and hot-swaps if that helps at all.

Learning from scratch so any tips are appreciated.

## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

**Comment by MikeWrock** [comment]
I have a fork that works on my k4v2 RGB, it's a hacked together mix of the sonix_qmk fork and this one to get CAPSWORD functionality. Tested on Ubuntu 22.04, I had to fork the sonix_flasher repo as well most likely due to my version of Ubuntu and python 2's deprecation. Give it a shot and let me know if it works

**Comment by MikeWrock** [comment]
The steps I used I wrote down in the readme
