### ISSUE TITLE
Can't the two IOs of B2 and A9 of the STM32F401 development board be used on the qmk, and cannot be used in the matrix. Is there any special usage or where do I need to set it up separately?

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#18312]
Can't the two IOs of B2 and A9 of the STM32F401 development board be used on the qmk, and cannot be used in the matrix. Is there any special usage or where do I need to set it up separately?
![image](https://user-images.githubusercontent.com/5648129/189142744-acdb2981-8732-40c1-8026-e48995494c0e.png)

**Comment by osamuaoki** [comment]
PA9-PA12 are shared with USB connection pins.  So they can't be used for key matrix fo QMK. 

OTG_FS_VBUS is subtle to be noticed but this is USB OTG I suppose.

I learned this hard way.

[Unusable pins](https://docs.qmk.fm/#/platformdev_blackpill_f411?id=unusable-pins)
* Pins A11 and A12 are not useable because they’re used for USB connection, and cannot be shared.
In theory, these pins can be used. However, doing so may disable USB connectivity, outright, if used for anything other than a USB port
* Pin B2 is used by BOOT1 and cannot be used, without causing problems.
* VBAT is not a usable pin.
* NRST is not a usable pin.
