### ISSUE TITLE
[Bug] `OSM()` does not work together with mouse clicks

### ISSUE THREAD

**Issue by mplattner** [qmk/qmk_firmware#18488]
Since I have a QMK keyboard I use `OSM(MOD_LCTL)` in my keymap to use the left CTRL key as a "sticky key".
Previously I did the same with the native Microsoft Windows sticky keys feature. With that, it was possible to hit the sticky key (e.g., CTRL) and then use the mouse to click on a link to open it in a new tab.

With QMK, however, that does not work. It only works if i _hold_ CTRL and then click, but not by just tapping CTRL and then click immediately after the release of CTRL.

According to the [one shot key docs](https://docs.qmk.fm/#/one_shot_keys?id=one-shot-keys) and to my understanding of it, it should work as expected in QMK:
> Your computer will see the shift key being held *the moment shift is pressed*, and it will see the shift key being released immediately after A is released.

Is this a bug or am I missing something?

My keyboard code is available at https://github.com/mplattner/qmk_firmware/tree/master/keyboards/sculpter/keymaps/mplattner

**Comment by drashna** [comment]
Could you check out the develop branch, and see if this is still the case?

**Comment by sigprof** [comment]
> Your computer will see the shift key being held the moment shift is pressed, and it will see the shift key being released immediately after A is released.

Looks like this part of the documentation is incorrect — it does not reflect the actual behavior of OSM keys in QMK.

Issue 1: Because OSM keys are implemented using the same `action_tapping.c` code that is also used for `LT()`/`MT()`, any OSM handling would be delayed until either the tapping term expires, or the OSM key is released (whichever happens earlier), or maybe some other action triggers early hold detection if one of the `PERMISSIVE_HOLD` or `HOLD_ON_OTHER_KEY_PRESS` is enabled for the OSM key. This also may cause other key events to be delayed until the tap/hold decision for the OSM key is completed.

Issue 2: The OSM tap is handled by calling `set_oneshot_mods()`, but those modifiers are not sent to the host immediately — instead, they are added only when `send_keyboard_report()` is called next time, which may happen only when another key is pressed.

It could be possible to change behavior described in “Issue 2” above by doing something like this (untested):
```c
void oneshot_mods_changed_user(uint8_t mods) {
    if (!oneshot_mods || !has_anykey(keyboard_report)) {
        send_keyboard_report();
    }
}
```
The `!has_anykey(keyboard_report)` check is needed to avoid sending the keyboard report immediately if any other keys are still held — otherwise `send_keyboard_report()` will immediately consume the one shot mods which are intended to be used for the next key press (so in this case the reporting of one shot mods will still be delayed as it is now).

Changing the part of the behavior described in “Issue 1” above would need some major changes, and I'm not sure that doing that would be possible at all. E.g., one of the features of the current implementation that some people really want is that the following sequence of events performed within the tapping term results in “Th”, not “TH”:
- press `OSM(MOD_LSFT)`
- press `KC_T`
- release `KC_T`
- press `KC_H`
- release `OSM(MOD_LSFT)` and `KC_H` (in any order, as long as `OSM(MOD_LSFT)` is released before its tapping term expires)

But handling this kind of sequence correctly requires delaying all events until the OSM key is released (only at that time the proper action of the OSM key can be determined). Although it might be possible to send the modifier report early even in this case, probably there would be some more corner cases (e.g., some other key pressed before the OSM key might not be released yet).

**Comment by mplattner** [comment]
Thanks @drashna and @sigprof. Your comments are kind of conflicting, as @drashna suggests this should be fixed already, and @sigprof suggests workarounds.

I'll soon test it with the current `develop` branch and update this issue.

**Comment by drashna** [comment]
Sigprof's response is much more correct. 

That said, there have been a number of changes to the mouse related keycodes to handle things better.  They may or may not help (and given what sigprof has said, won't help).

**Comment by mplattner** [comment]
I updated to 0.19.4, but the issue remains (as you expected). Sorry I only found time to test this after a while.

I haven't tested @sigprof's suggested workaround, but to my understanding only solving issue 2 (with the provided example code) is not enough anyway, right?

**Comment by T4CORUN** [comment]
I can confirm that OSM does not work together with mouse clicks. like @mplattner, I think this would be good to resolve
