### ISSUE TITLE
[Feature Request] Add support for DOIO Megalodon 38%

### ISSUE THREAD

**Issue by p1nkpoodle** [qmk/qmk_firmware#18918]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

The 16 key variant of this is already supported. Please could we add support for the 38 key version? I believe it uses ATmega32U4.

Product:
https://www.keebmonkey.com/products/megalodon-doio-triple-knob-38-keyboard-with-oled-screen?_pos=2&_sid=9590ce03a&_ss=r

Layout JSON:
https://wiki.keebmonkey.com/kb38.json.zip

16 key version:
https://github.com/qmk/qmk_firmware/tree/master/keyboards/doio/kb16

Thank you

**Comment by ThuckingKeyboard** [comment]
Please.. This would save people so much headache and actually allow people to customize their macropad to fit their needs. I mean, isn't that the whole point of a macropad?

**Comment by drashna** [comment]
At best, you'd need a multimeter to determine how the keyboard is laid out, and then build the config from there. 

But that means that somebody with one would need to do that.   

Mechmerlin has some nice youtube videos on how to port boards. 

The alternatives are either ask/demand that the seller provide source code for the board, since it's covered under the GPL and thus requires them to do so.  Or find somebody willing to port the boards.

**Comment by ThuckingKeyboard** [comment]
I appreciate the insight, thank you

**Comment by toddward** [comment]
@drashna do you know the process to start requesting that doio deliver the source?

**Comment by tzarc** [comment]
Unfortunately the QMK maintainers do not have access to these boards, so will be unable to help.
Your best bet is to go through the motions to add support yourself, then submit a Pull Request back to QMK.
