### ISSUE TITLE
[Bug] Can't use OLED and RGB Light at the same time

### ISSUE THREAD

**Issue by boulevard-h** [qmk/qmk_firmware#19245]
### Describe the Bug

My mcu is STM32F103cBt6, I use it to drive a I2C OLED screen and WS2812 RGB Light. The OLED and RGB can both work separately. When I only use RGB, it can work, but when a add the screen, only the screen works. However, when I remove the OLED (just plug it off, no change to the firmware), the RGB recume work.

RGB control pin is B5, and OLED I2C pins is B6&B7.

mcuconf.h:
![9`GL0MHUZ)OM85MH)0`D34T](https://user-images.githubusercontent.com/89329408/205938118-1e2eb7a3-de75-4d03-8ef1-d676cf85e181.png)

RGB Code:
![NMMIPOF_2P`6FN}UUS7RRD8](https://user-images.githubusercontent.com/89329408/205938308-f55fc7ed-e841-4a52-8e29-4f4e53452aec.png)

BTW, I also use the A1 pin for AUDIO to drive a buzzer:
![DEJ@WVJ8R()0EH2A7(XKSQO](https://user-images.githubusercontent.com/89329408/205938528-f69058a2-0dad-40d5-8ce2-9e47b5ab14ee.png)

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by sigprof** [comment]
Looks like you are hitting the erratum 2.3.8 from the [STM32F103x8/B errata sheet](https://www.st.com/resource/en/errata_sheet/es096-stm32f101x8b-stm32f102x8b-and-stm32f103x8b-mediumdensity-device-limitations-stmicroelectronics.pdf):
![Erratum 2.3.8](https://user-images.githubusercontent.com/616082/205944899-caa5d8a9-4ff9-49cd-820c-cb7600242fcc.png)
And you can't workaround that by using `WS2812_DRIVER = spi` because of the erratum 2.3.7:
![Erratum 2.3.7](https://user-images.githubusercontent.com/616082/205945480-90d5175c-f50e-4ac3-9282-90256b3f52b0.png)
So your options here are either using `WS2812_DRIVER = bitbang` (with the corresponding limitations) or modifying the hardware to use some other pins which won't be affected by the chip errata or any other resource conflicts (e.g., you can't use TIM4 for WS2812 together with I2C1 because of DMA conflict for `TIM4_UP`; and TIM1 for WS2812 won't work together with I2C2 for the same reason).

BTW, your audio configuration seems to be incorrect — pin A1 has `TIM2_CH2`, but your config is for `TIM1_CH1`.
