### ISSUE TITLE
[Bug] Python 3.10 Requirement

### ISSUE THREAD

**Issue by spencerthayer** [qmk/qmk_firmware#19882]
### Describe the Bug

I currently have the latest Python installed on Mac OS and QMK is looking for an older version.
```
/usr/local/bin/qmk: bad interpreter: /usr/local/Cellar/qmk/1.1.1/libexec/bin/python3.10: no such file or directory
```

Installing 3.10 with `brew install python@3.10` resolves this issue but the idea of running multiple versions of Python is bad practice. It's not like QMK is using Python 2 it's simply not allowing for very minor version update. Please consider fixing this bug.

**Comment by tzarc** [comment]
As far as I can tell, `qmk` only currently depends on `python`, not `python@3.10`:
https://github.com/qmk/homebrew-qmk/blob/master/Formula/qmk.rb#L26

**Comment by spencerthayer** [comment]
Which is all the more confusing why `brew install python@3.10` works.

**Comment by tzarc** [comment]
I'd imagine it's due to when the package was built. Have flagged it internally, someone with a bit more expertise in this area might have a bit more info.

Perhaps just a republish is in order? Unsure.

**Comment by ForsakenRei** [comment]
My two machines are running Python 3.9 and 3.10 but didn't have issue on both(Win and Arch though). 
I'm not a Mac user but this sounds like a Python issue rather than QMK issue. Probably check `which python` and then `ls -l` the path first?

**Comment by android606** [comment]
I can confirm this issue. I run `qmk setup` and get:
`zsh: /usr/local/bin/qmk: bad interpreter: /usr/local/Cellar/qmk/1.1.1/libexec/bin/python3.10: no such file or directory`

 Installing on Mac OS with `brew install qmk/qmk/qmk` creates a symbolic link `/usr/local/Cellar/qmk/1.1.1/libexec/bin/python3.10` that points to
`/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin/python3.10`

I don't have python 3.10 installed, so that symlink is dead. Homebrew has dependency for 'python' but installed python 3.11, and the symlink doesn't point to it. This would appear to be an issue with qmk cask.

**Comment by fauxpark** [comment]
I've updated the formula, please try it now.

**Comment by spencerthayer** [comment]
Working!
