### ISSUE TITLE
[Bug] raw_hid_receive only works intermittently

### ISSUE THREAD

**Issue by madwort** [qmk/qmk_firmware#20506]
### Describe the Bug

I've added this C snippet to my keymap.c to very simply copy raw hid messages to the oled & sent some messages to my splitkb/kyria with this python snippet. Anyway, it works, but not reliably - 1/3 the keyb oled displays the message correctly! but maybe 1/3 time python says "unable to open device" and 1/3 time the script completes but the oled doesn't update, I'm not sure why. I suspect some of my hid messages might be being captured by the keyboard's own handler - if the first byte is `\x01` & the python script manages to connect, I think it *either* turns on NumLock on my keyboard *or* displays my string. Are there deeper issues with the support for my keyboard that need to be fixed before I can use this reliably, or is there a magic spell that I can add in order that my messages don't get captured by any other handlers that may be running? (or are my C skillz too rusty...?)

keymap.c:

```c
...
#include "raw_hid.h"

...
    
char hidoutput[16] = "";

...

bool oled_task_user(void) {
    ...
    oled_write_P(PSTR(hidoutput), false);
    ...
}

void raw_hid_receive(uint8_t *data, uint8_t length) {
  for(size_t i = 0; i < 16; ++i)
  {
    hidoutput[i] = data[i];
  }
  oled_task();
}
```

myhidscript.py:

```python
import hid
import random

# splitkb kyria3
vid = 0x8d1d	# Change it for your device
pid = 0xcf44	# Change it for your device

with hid.Device(vid, pid) as h:
    mystring = f"Hello World {random.randint(100,999)}"
    h.write(mystring.encode('utf-8'))
    h.close()
```

### Keyboard Used

splitkb/kyria/rev3

### Operating System

macos

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.2
Ψ QMK home: /Users/tom/qmk_firmware
Ψ Detected macOS 13.2.1 (Intel).
Ψ Git branch: madwort/layout
Ψ Repo version: 0.20.5
⚠ Git has unstashed/uncommitted changes.
Ψ - Latest madwort/layout: 2023-04-17 13:21:51 +0100 (898f31d823) -- replace kyria logo with madwort logo
Ψ - Latest upstream/master: 2023-04-10 07:38:09 +1000 (fb706f42a2) -- Run CI builds for each push, limit queued workflow depth to 1. (#20362)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2023-04-10 07:38:09 +1000 (fb706f42a2) -- Run CI builds for each push, limit queued workflow depth to 1. (#20362)
Ψ - Common ancestor with upstream/develop: None
Ψ CLI installed in virtualenv.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 8.3.1
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 7.0
Ψ Found dfu-programmer version 1.0.0
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2023-01-03 19:29:26 +0000 --  (0062927e3)
Ψ - lib/chibios-contrib: 2023-01-11 16:42:27 +0100 --  (a224be15)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [X] Karabiner (macOS)

**Comment by elpekenin** [comment]
Some notes:
- Raw HID requires messages to be `RAW_EPSIZE`(32) bytes long, so you'd need the python code to add some padding (windows needs an extra heading byte and would be 33)
- I dont think `PSTR` and `oled_write_P` should be used as the `P` means "this string in stored in flash memory", but since your value is dynamic and not a compile-time known thing i dont know how it even got to work
- Your keyboard is reporting several HID endpoints (one for keyboard messages, another for RawHID, another for console if enabled and so on). Your code should filter by usage/usage-page pair, instead of the device id which will be common across all endpoints
- You could use `memcpy` instead of a loop to copy the text into the reception buffer
- I wouldn't call `oled_task` from the RawHID handler and just let it draw on the next cycle, time difference shouldnt be noticeable
- When you have a context manager (`with ...` block) it automatically closes the thing when you leave its scope, so the `h.close()` line should be safe to remove

Take a look at this for some implementation details <https://gist.github.com/fauxpark/03a3efcc7dbdfbfe57791ea267b13c55>
