### ISSUE TITLE
[Feature Request] Support Internal Reference of ADC for STM32F10X 

### ISSUE THREAD

**Issue by temp4gh** [qmk/qmk_firmware#21732]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

My hardware could not use ext reference of ADC for STM32F103 ，according to ST official sdk，there is a way to use 
 internal reference， I noticed that there is a define ‘’ADC_CHANNEL_VREFINT‘’ in file 'hal_adc_lld.h' for STM32F1xx ，but no related code was found to implement this function. Thanx!

**Comment by sigprof** [comment]
According to the reference manual, the internal reference is connected to the ADC1 channel 17, for which `lib/chibios/os/hal/ports/STM32/STM32F1xx/hal_adc_lld.h` has the `ADC_CHANNEL_VREFINT` define.  With the current QMK API the way to read from such extra channels is `adc_read(TO_MUX(ADC_CHANNEL_VREFINT, 0))` (here `0` represents the ADC1 peripheral — on STM32F103 the ChibiOS driver supports only ADC1 anyway, even if you have a larger chip which has ADC2 and ADC3).

However, another complication is that both the temperature sensor and the internal voltage reference are disabled by default, and controlled by the `TSVREFE` bit in `ADC_CR2`:
![reference manual](https://github.com/qmk/qmk_firmware/assets/616082/ef696ae5-5aa4-41d3-9dfb-143a6042ed15)
The state of that bit could be controlled through the `cr2` field in `ADCConversionGroup`, but in the current ADC driver code in QMK that field is not configurable.

(For some other STM32 chips the ChibiOS ADC driver provides functions like `adcSTM32EnableTSVREFE()`, but for STM32F103 that's not the case, probably because the `TSVREFE` bit on STM32F103 is in a register which is also used during normal ADC operation.)

In addition, apparently in the `smpr1` field only the bits for channels 10…15 are initialized, so probably `| ADC_SMPR1_SMP_AN16(ADC_SAMPLING_RATE) | ADC_SMPR1_SMP_AN17(ADC_SAMPLING_RATE)` would need to be added there.
