### ISSUE TITLE
I have 96 Layout keyboard with ATmega32a. Can I flash QMK follow this guide?

### ISSUE THREAD

**Issue by underpk** [qmk/qmk_firmware#2185]
Its 96 keyboard layout with arrow key. Can I flash QMK follow this guide? 

https://github.com/qmk/qmk_firmware/tree/master/keyboards/ymd96

I would like to try but I'm afraid if I flash something may go wrong.

**Comment by Duckle29** [comment]
@underpk As long as you don't flash the fuses of the chip so that flashing is disabled you should be fine. That means leaving either jtag or spi interfaces up. You're most likely using some sort of ISP, so that means don't dissable the SPIen flag in the high fuse: http://www.engbedded.com/fusecalc/

Note that on AVR a fuse bit of 0 = set and 1= not set

Another thing of note, is that if you set the fuses to require an external clock source, you have to have an external clock source to program it, so if your board has a crystal for the chip, that shoul be fine, but if not, don't set the clock source to anything but the internal clock.

If you stick to this, you should always be able to reflash it.

You might also want to read the flash, fuses and eeprom from the chip and save them as backups if you want to flash the original firmware on there. Keep in mind that you might not be able to do this. If the lock bits are set so that you can't read the device, then this is not an option.
