### ISSUE TITLE
Is it possible to keep the input from the previous layer when switching?

### ISSUE THREAD

**Issue by Miodec** [qmk/qmk_firmware#2279]
Its pretty hard to describe. Lets say im playing a game, and holding W. If i switch to a layer while holding w, is it possible to lock that input until i come back to the same layer? I tried doing it with kc_trans but that did not work. The second i switch layers (while holding w) - w is no longer sent as input. My poker worked like that, and i was wondering if its possible with qmk.

**Comment by drashna** [comment]
This is by design.  When switching layers, all pressed keys (that aren't mods) are cleared.  

You can see this here: https://github.com/drashna/qmk_firmware/blob/master/tmk_core/common/action_layer.c#L121

But as the comment indicates, this may not be a good idea, as keys can (would) get stuck.  Specifically, if the same key isn't on the destination layer and you let go of it ... it would get stuck pressed.  
Which is why it's handled this way by default.

**Comment by drashna** [comment]
This has been changed now.  Update your repo, and it should be the default behavior now.

You can revert by defining `STRICT_LAYER_RELEASE`.
