### ISSUE TITLE
make -- Keymap confused for target?

### ISSUE THREAD

**Issue by Justinicus** [qmk/qmk_firmware#2288]
Derp. Turns out I had two git repos, and I was working on one while trying to compile the other. I suspect that may have *something* to do with my problem.
------------------------------------------------------------------------
I'm a QMK noob, please help me learn!

I'm using the new mingw paradigm on Windows 10, if that makes a difference. I copied and renamed the keymaps\default to keymaps\justinicus in my own fork.  I'm trying to compile my modded keymap for the first time, and getting the following results:

```
$ make ergodox_infinity:justinicus
QMK Firmware 0.5.207
Making ergodox_infinity with keymap 333fred and target justinicus
                              [ERRORS]
make[1]: *** No rule to make target 'justinicus'.  Stop.
Making ergodox_infinity with keymap ab and target justinicus
                                   [ERRORS]
make[1]: *** No rule to make target 'justinicus'.  Stop.
Making ergodox_infinity with keymap absenth and target justinicus
                             make: *** [Makefile:542: ergodox_infinity:justinicus] Interrupt

```

It seems to be treating my keymap as a target. What am I doing wrong? Did I miss a step in creating my own keymap?

Edit: probably should have mentioned that `make ergodox_infinity:default` works just fine. My fork's keymaps folder is here: https://github.com/Justinicus/qmk_firmware/tree/master/keyboards/ergodox_infinity/keymaps

**Comment by drashna** [comment]
make sure the spelling is correct.  Otherwise, it does attempt to compile for me.

~~`TAPPING_TOGGLE` is already defined, so you need to add `#undef TAPPING_TOGGLE` first, or use the default of "1".~~

~~For the layers, you can't have "QWERTY" as both the layer number, AND a keycode.  My recommendation is to use `_QWERTY` for the layers. Less changes needed.~~

~~For the keycodes, you only need `SAFE_RANGE` on the first.  That way, it starts in the safe range, and will automatically increment up, from there.~~


I fixed most of the issues with this: https://gist.github.com/drashna/b78a6185ec6e327a44eb17ad0bcb5195
