### ISSUE TITLE
[Bug] Keychron Q4 doesn't boot since ChibiOS update

### ISSUE THREAD

**Issue by juliekoubova** [qmk/qmk_firmware#23820]
### Describe the Bug

I bisected between `0.24.11` and current `master`, and nothing after #23405 boots up on my Keychron Q4. It doesn't seem to talk to the host, there's nothing in `dmesg` after STM32 BOOTLOADER disconnects. Please let me know if I can help debugging this in any way.

### Keyboard Used

keychron/q4/ansi/v2

### Operating System

Alpine Linux edge

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by sigprof** [comment]
The likely culprit is https://github.com/qmk/ChibiOS/commit/392367e7a9aff94020ffdc59b3ef8c0de07ad1e6 (https://github.com/ChibiOS/ChibiOS/commit/ebc36356e60cc0941058219bfbe9187c03cb6794 in the official mirror) — that change does not look correct, and probably results in testing of the LSERDY bit instead of the intended LSIRDY, therefore the wait loop becomes infinite.  The affected `stm32_lsi.inc` file is used by the code for the G0xx, G4xx, L4xx, L4xx+, L5xx, MP1xx, WLxx families.
