### ISSUE TITLE
[Bug] autoshift interferes with autocorrect

### ISSUE THREAD

**Issue by grasegger** [qmk/qmk_firmware#23853]
### Describe the Bug

When auto shift is enabled auto correct does not trigger any corrections. Once auto shift is disabled auto correct works as expected. 

In a debug log I tested if the keys are going through the auto correct function at all and it looked like only space is processed, so auto shift is capturing the alpha keys and not letting auto correct process them.

I am reporting this as a bug since the expectation was that those two features do not interfere.

### Keyboard Used

anna_x (sources linked below)

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.5
Ψ QMK home: /home/karl/qmk_firmware
Ψ Detected Linux (WSL, Debian GNU/Linux 12 (bookworm)).
Ψ Userspace enabled: False
Ψ Git branch: anna_x
Ψ Repo version: 0.25.4
Ψ - Latest anna_x: 2024-06-02 10:40:17 +0200 (9872d69491) -- cleanup
Ψ - Latest upstream/master: 2024-06-01 10:37:40 +1000 (fa6d23235b) -- [docs] Remove gitbook directory (#23839)
Ψ - Latest upstream/develop: 2024-06-01 00:38:08 +0000 (6c87500231) -- Merge remote-tracking branch 'origin/master' into develop
Ψ - Common ancestor with upstream/master: 2024-06-01 10:37:40 +1000 (fa6d23235b) -- [docs] Remove gitbook directory (#23839)
Ψ - Common ancestor with upstream/develop: 2024-06-01 10:37:40 +1000 (fa6d23235b) -- [docs] Remove gitbook directory (#23839)
Ψ CLI installed in virtualenv.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 12.2.1
Ψ Found avr-gcc version 5.4.0
Ψ Found avrdude version 7.1
Ψ Found dfu-programmer version 0.6.1
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2024-02-17 19:20:06 +0000 --  (be44b3305)
Ψ - lib/chibios-contrib: 2024-04-03 20:39:24 +0800 --  (77cb0a4f)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Additional Context

sources: https://git.sr.ht/~grasegger/QMK/tree/anna_x/item/keyboards/anna_x

**Comment by drashna** [comment]
For reference:
https://discord.com/channels/440868230475677696/869812721552601088/1249274505617084466

(this may not be a fix, but references some potentially useful info)

**Comment by ancyberturtle** [comment]
I know this is closed but I had the same issue. I was able to get a solution when chatting with claude.  

<html>
<body>
<p dir="ltr"><code>process_record_quantum</code> calls the feature processors in a fixed order:</p>
<div dir="ltr">
Line | Call
-- | --
355 | process_record_kb → process_record_user
399 | process_auto_shift
426 | process_autocorrect

</div>
<p dir="ltr">Each returns <code>bool</code>; <code>false</code> halts the chain.</p>
<p dir="ltr">Auto Shift's whole design is deferral. On key-down of an auto-shiftable key it records the keycode and timestamp, then returns <code>false</code> — it can't know yet whether you want <code>a</code> or <code>A</code>. That <code>false</code> stops processing at line 399, so <strong>line 426 is never reached</strong>.</p>
<p dir="ltr">On release (or timeout) it emits the key with <code>register_code16()</code> / <code>unregister_code16()</code>. Those write straight to the HID report; they don't re-enter <code>process_record</code>.</p>
<p dir="ltr">Result: autocorrect's typo buffer sees only keys Auto Shift ignores — space, punctuation outside the symbol set, backspace. Since corrections are triggered by the buffer ending in a known typo, and the typo letters never arrive, nothing ever matches. Not "sometimes flaky" — structurally zero corrections.</p>
<h4 dir="ltr">The fix</h4>
<p dir="ltr"><code>process_record_user</code> runs at line 355, ahead of Auto Shift. Feed it the keys Auto Shift is about to swallow:</p>
<div role="group" aria-label="c code" tabindex="0"><div><div></div></div><div>c</div><div><pre style="color: rgb(234, 236, 240); background: transparent; font-family: var(--font-mono);"><code class="language-c" style="color: rgb(234, 236, 240); background: transparent; font-family: var(--font-mono); white-space: pre;"><span style="color: rgb(204, 123, 244);">if</span> <span style="color: rgb(211, 215, 222);">(</span>record-&gt;event.pressed
    &amp;&amp; <span style="color: rgb(112, 184, 255);">get_autoshift_state</span><span style="color: rgb(211, 215, 222);">()</span>
    &amp;&amp; <span style="color: rgb(211, 215, 222);">(</span><span style="color: rgb(112, 184, 255);">get_mods</span><span style="color: rgb(211, 215, 222);">()</span> | <span style="color: rgb(112, 184, 255);">get_oneshot_mods</span><span style="color: rgb(211, 215, 222);">())</span> == <span style="color: rgb(94, 237, 237);">0</span>
    &amp;&amp; <span style="color: rgb(112, 184, 255);">get_auto_shifted_key</span><span style="color: rgb(211, 215, 222);">(</span>keycode<span style="color: rgb(211, 215, 222);">,</span> record<span style="color: rgb(211, 215, 222);">))</span> <span style="color: rgb(211, 215, 222);">{</span>
    <span style="color: rgb(204, 123, 244);">if</span> <span style="color: rgb(211, 215, 222);">(</span>!<span style="color: rgb(112, 184, 255);">process_autocorrect</span><span style="color: rgb(211, 215, 222);">(</span>keycode<span style="color: rgb(211, 215, 222);">,</span> record<span style="color: rgb(211, 215, 222);">))</span> <span style="color: rgb(211, 215, 222);">{</span>
        <span style="color: rgb(204, 123, 244);">return</span> <span style="color: rgb(94, 237, 237);">false</span><span style="color: rgb(211, 215, 222);">;</span>
    <span style="color: rgb(211, 215, 222);">}</span>
<span style="color: rgb(211, 215, 222);">}</span></code></pre></div></div>
<p dir="ltr">The gate must <strong>exactly mirror Auto Shift's capture condition</strong>, or keys get fed twice — once here and again at line 426 — corrupting the typo buffer. Each clause earns its place:</p>
<ul dir="ltr">
<li><strong><code>record-&gt;event.pressed</code></strong> — autocorrect ignores releases; feeding them wastes cycles and risks double-counting.</li>
<li><strong><code>get_autoshift_state()</code></strong> — runtime state, not compile-time. With Auto Shift toggled off via <code>AS_TOGG</code>, keys flow normally to 426, so feeding them here would double-process.</li>
<li><strong><code>(get_mods() | get_oneshot_mods()) == 0</code></strong> — Auto Shift skips modified presses by default, so those also reach 426 on their own.</li>
<li><strong><code>get_auto_shifted_key()</code></strong> — the authoritative predicate, so the gate tracks any <code>NO_AUTO_SHIFT_*</code> config automatically instead of hardcoding a key list.</li>
</ul>
<p dir="ltr">Returning <code>false</code> when autocorrect returns <code>false</code> matters. Reading the correction path: on a match it taps backspace <em>n</em> times, sends the replacement, and returns <code>false</code> to suppress the triggering keypress. Propagating that stops Auto Shift ever seeing the key, so it doesn't append the final letter after the correction — the same net behaviour as the plain non-Auto-Shift path.</p>
<p dir="ltr">Both includes need <code>#ifdef AUTO_SHIFT_ENABLE</code> guards so the keymap still builds with the feature off.</p>
</body>
</html>
