### ISSUE TITLE
Change hamburger menu placement

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#2918]
As pointed out on reddit we need to change how the hamburger menu works: https://www.reddit.com/r/olkb/comments/8huf00/qmk_proposed_replacement_for_gitbook_feedback/dyn8qoi/

We're looking for a frontend developer who can either work some CSS magic or write a docsify plugin to make that menu behave more sanely.

**Comment by aergonaut** [comment]
Looking at the CSS in `qmk.css`, the hamburger has `position: fixed` and `bottom: 0`, which is what sticks it to bottom. Changing to `top: 0` instead would stick it to the top, but that leads to the hamburger overlapping the search field:

![hamburger overlaps search field when stuck to top](https://cl.ly/rUS2/[3f2070d7bcc6e6d9b1bea3b8d7ec938c]_Screen%20Shot%202018-05-09%20at%2023.46.32.png)

You could shift the search bar down, but that ends up leaving about 40px (I eyeballed) of negative space:

![negative space left in sidebar](https://cl.ly/rV8V/[849f7db81c244b07d1a336dfb3ef374b]_Screen%20Shot%202018-05-09%20at%2023.49.55.png)

I thought the negative space would look stranger, but after trying it out, it doesn't really look that weird. So that could be an option.

The CSS for when the sidebar is collapsed seems to just leave a gutter where the hamburger sits, so moving it up to the top doesn't seem to affect the usability of the site in that state.

**Comment by aergonaut** [comment]
@skullydazed yes, I'd be happy to make a PR. I'll need to read a little about how docsify works, since I've never used it before, but I should be able to get a PR up for you in the next couple of days.
