### ISSUE TITLE
JJ40 Backlight - only 3/5 lights turn on

### ISSUE THREAD

**Issue by j-chan-hkust** [qmk/qmk_firmware#3199]
For reference I have loaded a slightly modified version of the suzuken keymap onto the board, with no alterations to any other code.

Right from the beginning, only 3 of the 5 leds turn on. I have already successfully updated the firmware, however the issue persists.

Another issue I have found is if you activate caps lock (either through on screen or laptop keyboard) you will cause the keyboard to become unresponsive.

could anyone give me some insight behind the source of the bugs?

**Comment by wanleg** [comment]
have you seen this post yet?
https://www.reddit.com/r/olkb/comments/8en8f1/strange_caps_lock_behavior/
i don't want/have LEDs on my JJ40, but i did have that caps lock issue (now fixed for me). 
as @Oscillope mentioned, it may have been an update to backlight behaviour.

**Comment by krusli** [comment]
Are the 5 LEDs you’re referring to the underglow LEDs? I would try a reflash at the very least (with bootloadHID) as it usually seems to clear up issues.

I’ll try to look into the CapsLock freezing issue once I have time — I ported the backlighting code from the original Bootmapper (PS2AVRGB) firmware but I might’ve made a mistake there (I didn’t have Caps Lock on my original keymap). Since the keyboard does not have an individual Caps Lock LED I think the entire block can be disabled/removed without much effect.

I’ll open up a new issue (or update here) once I get around to fixing it. Sorry for any problems you’ve been encountering from my backlight support patches!

**Comment by Rulevoid** [comment]
I have a related issue, thus not opening a new issue.  All of my backlights turn on by default and are red after flashing with BootloaderHID (qmk toolbox doesn't recognize this pcb for me).  My issue is none of the qmk configurator BL keycodes are doing anything.

**Comment by drashna** [comment]
@Rulevoid To make sure, you are using the RGB_* keycodes, and not the BL_*/backlight keycodes.

**Comment by Rulevoid** [comment]
@drashna That was the issue!  Thank you!
