### ISSUE TITLE
Adafruit Bluefruit 32u4: OUT_AUTO not applied by default

### ISSUE THREAD

**Issue by Miodec** [qmk/qmk_firmware#3577]
Pretty much what #2229 describes - the keyboard is not applying out_auto by default and sends keycodes on both usb and bluetooth.

**Comment by RcColes** [comment]
This is because setting ```BLUETOOTH = AdafruitBLE``` defines ```BLUETOOTH ENABLE```, and whenever ```BLUETOOTH_ENABLE``` is defined the default output is set to ```OUTPUT_USB_AND_BT```.

This can be pretty trivially changed with minimal effect on current bluetooth keyboards by putting in an ```ifdef MODULE_ADAFRUIT_BLE``` and setting the default output properly. I've got a version with this change done and it works great, and I can put together a PR if it's wanted.

I'd definitely be in favour of a change to this - it makes adafruit BLE keyboards much more usable because without this change the user has to manually control the output (which is what my previous workaround was), or alternatively just not have both connected at once.
