### ISSUE TITLE
Reference glossary incorrectly defines "scancodes"

### ISSUE THREAD

**Issue by TaranVH** [qmk/qmk_firmware#4429]
https://beta.docs.qmk.fm/reference/reference_glossary
If you search the linked HID usage tables document for "scan code" or "scancode," you will find nothing. Only "key codes" are represented. And those numbers are definitely different from scancodes. They seem to be in alphabetical order... while scancodes are in QWERTY order (mostly.)

Now, there seem to be differing definitions on what a "scancode" or "scan code" is. Intercept.exe and [AutoHotKey use a 3-digit number to represent them](https://jacksautohotkeyblog.wordpress.com/2016/04/14/understanding-autohotkey-keyboard-scan-codes-and-virtual-key-codes-beginning-hotkeys-part-12/) - and I have reason to believe that it only goes as high as SC1FF, though I haven't actually tried it yet.

Anyway, what I'm really trying to do, is to find a way to send arbitrary scan codes, using a QMK keyboard. Like, if I press Z, I might want it to send SC090, rather than SC02C as it usually would. X would send SC091, and so on. Is that even possible with QMK?

[This guy seems to be having the same issues that I am.](https://www.reddit.com/r/olkb/comments/8me48x/understanding_qmktmk_scancodes_and_adding_our_own/) He's come up short so far...

**Comment by fauxpark** [comment]
Unfortunately it's not possible for QMK to change what "scancode" a key produces (as AutoHotKey sees them), because it simply doesn't send them. There is a difference between the "keycodes" you add to your keymap, and the "scancodes" that it actually sends over the wire.

In this case a **keycode** is a 16-bit value (0-65535) that allows support for many of the main QMK features like Mod-Tap, layer switching, RGB/backlighting etc. Obviously these aren't transmitted to the computer, at least not as-is. For ease of use, they are given aliases like `KC_A`, `RESET`, `MT()`.

A **scancode** according to QMK is an 8-bit number (0-255) which are your basic keys like the alphanumerics, arrow keys, F keys and so on, as defined by the HID usage tables. If the keycode you just pressed in your keymap is within this range (more or less, there are some empty spots in the spec that have been filled by eg. mouse keys and media keys) it is simply added to the keyboard report to be sent, otherwise QMK handles it and performs a layer switch, or a macro, or whatever.

What AutoHotKey is seeing is the codes that Windows or the kernel has mapped from the HID keycodes. That article describes "scan codes" as being on the hardware side - which is sort of true, if you're using a PS/2 keyboard. But even those keyboards actually send two different codes on press and release, so it is not quite that simple.
