### ISSUE TITLE
F12 - 24 Keys not working on Massdrop CTRL

### ISSUE THREAD

**Issue by M1K8** [qmk/qmk_firmware#4548]
When assigning any keycode between F13-F24, nothing happens when they key is pressed. This happens with both the online configurator when manually building the firmware. register_code() and unregister_code() are also non-functional with these keycodes.

**Comment by drashna** [comment]
I think this may actually be an OS issue, and not keyboard/QMK related.

Are you using something to keep track of the outputs and seeing  if the OS is receiving anything, at all?

**Comment by M1K8** [comment]
Yep, and the OS isn't receiving anything. Strangely enough if I use another qmk keyboard, the additional f keys work fine. This issue also persists across multiples machines

**Comment by M1K8** [comment]
The keyboards where the f keys work fine are using a AT90USB646 and a 32u4, whilst the problematic keyboard is using a ATSAMD51J18A.

**Comment by fauxpark** [comment]
This is probably because the ATSAM HID report descriptor [only declares usages up to `0x65`](https://github.com/qmk/qmk_firmware/blob/master/tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.c#L112), and the F13-F24 keys are `0x68` through `0x73`. If you change the Usage Maximum and Logical Maximum to `0xFF` it should work.

**Comment by M1K8** [comment]
That fixed it, thanks!

**Comment by patrickmt** [comment]
@M1K8 just to be clear, did you increase both `Usage Maximum` and `Logical Maximum` to `0xFF` as suggested by @fauxpark for the correct functionality?
