### ISSUE TITLE
Document Chibios/ARM stuff from #465

### ISSUE THREAD

**Issue by jackhumbert** [qmk/qmk_firmware#466]
https://github.com/fredizzimo/infinity_ergodox/blob/master/README.md

**Comment by fredizzimo** [comment]
There are also some more documentation in https://github.com/jackhumbert/qmk_firmware/tree/master/tmk_core/protocol/chibios. But that's mostly internal stuff, and some of it isn't relevant anymore.

For the required packages, I'm testing the different Vagrant configurations and updating the avr_setup.sh script now. So once that's done the correct packages should be added to the documentation. I also think the the documentation should primarily refer to running that script, instead of running the install commands manually.

**Comment by fredizzimo** [comment]
I think the general build setup instructions and the keyboard specific ones have enough information now.
