### ISSUE TITLE
Default Preonic rev 3 file is a hex file. This should be a .bin file.

### ISSUE THREAD

**Issue by shmcgrath** [qmk/qmk_firmware#4953]
The autogen script in QMK Toolbox does not work properly for Preonic v3. It generates a .hex file when it should be a .bin. I believe the [keyboards] page on the docs also points to an incorrect download file.
![preonic-v3-default](https://user-images.githubusercontent.com/877042/51793551-0edecb00-2190-11e9-8d34-c8956161b084.png)

**Comment by samirmakwana** [comment]
Noticed that on my system too. Windows 10 64bit. But when I used msysw64 in command line to make a file, it generated a .bin file. May be you could give that a shot?

**Comment by noroadsleft** [comment]
Need to add Planck rev6 to this issue also.

**Comment by drashna** [comment]
Okay, I looked into this.

The issue is that the Travis build scripts create a HEX file for this, no matter what the normal output would be.  Also, the scripts only look for HEX files, not BIN.  

I've created a PR that should address both issues.

The caveat is that both the qmk.fm website, and the toolbox may need to be updated to use these files properly.
