### ISSUE TITLE
Key-code don't match input

### ISSUE THREAD

**Issue by JonathanBartley** [qmk/qmk_firmware#6526]
I flashed my Idobo keyboard with the key code (KC_QUOTE), however instead of inputing  (' and ") it inputs(: and *). there are a few other key codes that are affected such as (KC_SCLN), (KC_LBRC) and more. Please help.

**Comment by fauxpark** [comment]
Sounds like your keyboard is set up as a Japanese (JIS) layout, on the OS side. I can reproduce this on Windows 10 by going to the Language settings, clicking the Options button on the Japanese "Preferred language", and switching the Hardware keyboard layout to "106/109 key" instead of "101/102 key".

**Comment by JonathanBartley** [comment]
Thank you Very much, that fixed the problem.
