### ISSUE TITLE
DZ68RGB only polls at 125hz

### ISSUE THREAD

**Issue by MatthewRobo** [qmk/qmk_firmware#6622]
## Describe the Bug
While the DZ60RGB polls at 1000hz, the DZ68RGB polls at only 125hz, making the typing experience sluggish.

## System Information

 - Keyboard:  DZ68RGB
   - Revision (if applicable):  
 - Operating system: Windows 10
 - AVR GCC version: (AVR_8_bit_GNU_Toolchain_3.6.1_1752) 5.4.0

 - ARM GCC version: (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

 - QMK Firmware version: 0.6.462

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by fauxpark** [comment]
The DZ60RGB does not poll at 1000Hz - in fact, none of the ChibiOS or AVR boards do:

https://github.com/qmk/qmk_firmware/blob/5ef7367e6c9adbaab3d91a52ad0fccace1c4b34f/tmk_core/protocol/usb_descriptor.c#L363

`0x0A` = 10ms (actually 8, because something something USB spec) = 125Hz

I plan to pull this out into a configurable define, after the `future` arrives :)
