### ISSUE TITLE
Add the approx memory taken up by each feature in the docs

### ISSUE THREAD

**Issue by alexweininger** [qmk/qmk_firmware#6944]
This is a pure documentation request.

## Description

I think that it would be helpful on pages like the [Tap Dance Feature](https://docs.qmk.fm/#/feature_tap_dance) I think it might be useful to have an approximate for how much memory this feature might add to the firmware size in a more prominent location on each feature page.

For example on the tap dance page it is only mentioned in the doc. And others I wasn't able to find an approximate.

![image](https://user-images.githubusercontent.com/12476526/66274269-8857ae80-e831-11e9-9fe3-1e68de83e205.png)

Thanks. Happy Hacktoberfest!

**Comment by yanfali** [comment]
@thomasbaart care to contribute?

**Comment by splitkb** [comment]
I made a guide on [how to save firmware space](https://thomasbaart.nl/2018/12/01/reducing-firmware-size-in-qmk/) at one point. Having that information be in the docs would be nice indeed, but is susceptible to enabling link time optimization and perhaps also by whether you'd use AVR or ARM.

I don't currently have the time to put into it, but there's at least a base to start from I suppose.

**Comment by zvecr** [comment]
As a note to link things together, there is #6947 (and #5488) which does the opposite.

**Comment by drashna** [comment]
I disagree with adding the firmware size for each feature.  At best, we should put a ballpark size. 

The reasoning behind this: 
* Different OS' use different versions of GCC, and different version compile different.  8.3 compiles to the smallest size, while 9.x is VERY large by comparison, even more so than 5.x or 6.x
* Some features have specific exceptions/handling based on what other features are enabled. Also, some code may be optimized away (due to redundancy) when multiple features are enabled.  And vice versa, too. 
* Link Time Optimization drastically reduces the compile size in many cases, dropping the size considerably. 

Because of these issues, having a stated size doesn't make sense, IMO, because then we have moving targets that may or may not be correct.... which is precisely why we have PRs removing these numbers.

**Comment by sakshamtaneja21** [comment]
i can help in this

**Comment by tzarc** [comment]
Going to go ahead and close this; different MCUs, different compilers, different compilation flags -- far too many combinations to keep track of, and far too many to keep up to date.

Ultimately, people only find a problem when things don't fit -- they very rarely if ever "plan to fit features X, Y, and Z" based on arbitrary firmware sizes.
