### ISSUE TITLE
Additional information to add in the help

### ISSUE THREAD

**Issue by mystcreater** [qmk/qmk_firmware#764]
Hi,

In the help, you talk about how to add a behavior to send some keys when one key is press and combined with another one and send another key when just tap.

You reference: MT(MOD_LCTL | MOD_LSFT, KC_ESC)

While building the hex file, I receive a warning indicating some parentheses are missing.

Here is what we should see in the documentation:

MT((MOD_LCTL | MOD_LSFT), KC_ESC)

After doing that, the warning disappears.

I've searched on the keymaps for of Ergodox and few people seems to use it.

**Comment by DidierLoiseau** [comment]
I think it is actually the macro definition which is wrong. There should be parenthesis around each macro argument. So instead of
```c
#define MT(mod, kc) (kc | QK_MOD_TAP | ((mod & 0xF) << 8))
```
it should be
```c
#define MT(mod, kc) ((kc) | QK_MOD_TAP | (((mod) & 0xF) << 8))
```
and similar for all macros… everywhere actually. Or replace it with an `inline` function.

See also [The need for parenthesis in macros in C](http://stackoverflow.com/q/10820340/525036).
