### ISSUE TITLE
BM40HSRGB Support[Feature Request] 

### ISSUE THREAD

**Issue by Fenlair** [qmk/qmk_firmware#9463]
I would like to add support for the KPRepublic Hotswap BM40RGB PCB.

## Description

The BM40RGB has kbfirmware support. I'd like to port it to qmk firmware. My plan was to use https://noroadsleft.github.io/kbf_qmk_converter/, if needed fix it up so it passes the coding guidlines and add a default keymap.

Would that be acceptable?

**Comment by sigprof** [comment]
This is a perfectly fine way to add support for a PCB to QMK — I did exactly this when [adding the ID80 support](https://github.com/qmk/qmk_firmware/pull/8728) (although that PR is probably more complicated than usual, because it also had some changes to optimize the somewhat unusual matrix layout, which hopefully won't be needed for BM40RGB).

One part which could bring some difficulties is that, unlike my ID80 example, BM40RGB has per-switch RGB backlight, for which the [RGB Matrix](https://docs.qmk.fm/#/feature_rgb_matrix) feature should be used (more common underglow LEDs are usually handled using [RGB Lighting](https://docs.qmk.fm/#/feature_rgblight) instead). Configuring the rgbmatrix code could be complicated; you can look at [this example of adding the BM60RGB support](https://www.reddit.com/r/MechanicalKeyboards/comments/elmt9k/porting_with_ports_kp_republic_bm60_rgb/).

**Comment by Fenlair** [comment]
Thanks for the info. I set everything up and it compiles, but especially for the RGB Matrix I need the PCB first to test it.
I will get a bm40rgb in a month or two and I plan to do a pull request when I tested my patch.

**Comment by sigprof** [comment]
I just realized that the Reddit link about BM60RGB that I provided does not point to the actual video (it is just a link to the Twitch channel, and that particular video is not even available in archive). See [Porting with Ports: BM60 RGB on Youtube](https://www.youtube.com/watch?v=KfPNSDZFxrY) instead.

**Comment by Fenlair** [comment]
no worries I found it without an issue after I knew it existed :)

Btw if someone owns a bm40rgb and doesn't want to wait for 2 months, send me a message.

**Comment by tmaj87** [comment]
> Btw if someone owns a bm40rgb and doesn't want to wait for 2 months, send me a message.
Hey, do you have working *.hex file?
